rest: /users for adding users to DB from CSV file
m-kuzmin/simple-rest-api pull request #1
Opened 2023-07-27 08:20 UTC by m-kuzmin

# Changelog

- Added `PUT /users` endpoint
    - Doc comments for swagger documentation tool.
    - `httptest` tests that test errors and successful DB entries
- Added an interface for querying the DB
- Updated linter rules

2023-07-28 09:07 UTC, penkova requested changes

2023-07-28 09:07 UTC, penkova commented on api/server.go
> +	users := make([]db.User, len(records))
You can simplify it. To enhance code readability, let's move the FOR logic responsible for creating users batch to a separate method. This will make the code more organized and easier to understand.

2023-07-28 09:07 UTC, penkova commented on api/server.go
> +// .
:) do you really need this coma?

2023-07-28 09:07 UTC, penkova commented on logging/stdlogger.go
> +	log.Printf("[debug      ] %s", fmt.Sprintf(s, a...)) //nolint:forbidigo // Allowed here only
Why trace and debug is in lowercase? :)

2023-07-28 09:07 UTC, penkova commented on main.go
> +func main() {}
why this is empty?

2023-07-28 09:07 UTC, penkova commented on main.go
> +func main() {}
how you run it?

2023-07-28 10:19 UTC, m-kuzmin commented on api/server.go
> +// .
It was there because of a linter I will disable

2023-07-28 10:22 UTC, m-kuzmin commented on logging/stdlogger.go
> +	log.Printf("[debug      ] %s", fmt.Sprintf(s, a...)) //nolint:forbidigo // Allowed here only
In the daily reporter logger all log levels were the same. It was hard to read the output when you have all levels enabled. Here I decided to make debug and trace be lowercase for readability and also add a character on the right of info, warning, error and fatal to make it easier to look at the output of the logs in the console.

2023-07-28 10:25 UTC, m-kuzmin commented on main.go
> +func main() {}
Ill copy the code from tests to at least start a runtime DB. The reason I didnt add it in the first place is because I was waiting for the postgres code to be merged and add a real db without having this intermediate in memory db.

2023-07-31 12:22 UTC, penkova commented on logging/stdlogger.go
> +	log.Printf("[debug      ] %s", fmt.Sprintf(s, a...)) //nolint:forbidigo // Allowed here only
ok, just strange that info, warning,error and fatal  in capital, but bug is lower

2023-07-31 12:24 UTC, penkova commented on main.go
> +	router := api.NewGinRouter(server)
create a task in project for the next changes: Add graceful shutdown

2023-07-31 12:24 UTC, penkova approved these changes

2023-07-31 13:35 UTC, merged